### ISSUE TITLE
Client n'ajoute pas les contact après les avoir acceptés

### ISSUE THREAD

**Issue by kiwixz** [kiwixz/babel#37]

**Comment by kiwixz** [comment]
Il attend la confirmation du serveur: @marinij doit confirmer que le serveur envois au deux

**Comment by marinij** [comment]
le serveur envoie le CONTACT_ADDED que à celui qui à fait la demande de contact.
je pensais que celui qui accepte la demande n'a pas besoin de recevoir le CONTACT_ADDED vu que c'est lui qui a accepté, il a pas vraiment besoin d'avoir de message du serveur. 
Mais c'est reglé du coup

**Comment by marinij** [comment]
Je dois faire la meme chose avec CALL_ACCEPTED ?

**Comment by marinij** [comment]
pardon
